MODEL:
  TYPE: resnet_2
  NUM_CLASSES: 10
  DEPTH: 18
BN:
  ZERO_INIT_FINAL_GAMMA: True
OPTIM:
  BASE_LR: 0.1
  LR_POLICY: steps
  STEPS: [0] #[0, 30, 60, 90]
  MAX_EPOCH: 5
  MOMENTUM: 0.9
  NESTEROV: False
  WEIGHT_DECAY: 0.0005
TRAIN:
  DATASET: CIFAR10
  SPLIT: train
  BATCH_SIZE: 256
  IM_SIZE: 32
  EVAL_PERIOD: 5
TEST:
  DATASET: CIFAR10
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 32
NUM_GPUS: 4
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
OUT_DIR: .
LOG_PERIOD: 50
ACTIVE_LEARNING:
  BUDGET_SIZE: 5000
